"""empty message

Revision ID: ae910f7aa6cc
Revises: 
Create Date: 2024-03-18 18:30:15.106858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae910f7aa6cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usr', 'person',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('usr', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usr', sa.Column('user_id', sa.VARCHAR(length=20), nullable=False))
    op.alter_column('usr', 'person',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
